import pandas as pd

df = pd.read_csv("Project+1+-+Weather+Dataset.csv")
print(df.nunique())
print(df['Wind Speed_km/h'].nunique())
print(df['Wind Speed_km/h'].unique())
print(df['Weather'].value_counts())
print(df[df.Weather == 'Clear'])
print(df.groupby('Weather').get_group('Clear'))
print(df[df['Wind Speed_km/h'] == 4])
print(df.isnull().sum())
print(df.notnull().sum())
df.rename(columns={'Weather': 'Weather Conditions'}, inplace=True)
print(df.columns)
print(df.Visibility_km.mean())
print(df.Press_kPa.std())
print(df['Rel Hum_%'].var())
print(df['Weather Conditions'].value_counts())
print(df[df['Weather Conditions'] == 'Snow'])
print(df[df['Weather Conditions'].str.contains('Snow')].tail(50))
print(df[(df['Wind Speed_km/h'] > 24) & (df['Visibility_km'] == 25)])
print(df.groupby('Weather Conditions').mean(numeric_only=True))
print(df.groupby('Weather Conditions').min(numeric_only=True))
print(df.groupby('Weather Conditions').max(numeric_only=True))
print(df[df['Weather Conditions'] == 'Fog'])
print(df[(df['Weather Conditions'] == 'Clear') | (df['Visibility_km'] > 40)])
print(df[(df['Weather Conditions'] == 'Clear') & (df['Rel Hum_%'] > 50) | (df['Visibility_km'] > 40)])
